---

gradientMode: "hue"
cellIdPreamble: "cell-"
cells: 
  metrics-per-sec:
    dataRef: "telegraf-metrics-per-sec"
    label:
      separator: "cr"
      units: "none"
      decimalPoints: 0
    labelColor:
      thresholdsRef: "queuecount"
    linkRef: "metrics-per-sec"
  write-time:
    dataRef: "telegraf-write-time"
    label:
      separator: "cr"
      units: "ns"
      decimalPoints: 2
    labelColor:
      thresholdsRef: "write-time"
    linkRef: "grafana-home"
  mem-usage:
    dataRef: "telegraf-mem-usage"
    label:
      separator: "cr"
      units: "pps"
      decimalPoints: 0
    labelColor:
      thresholdsRef: "queuedepth"
    linkRef: "grafana-home"