---

gradientMode: "hue"
cellIdPreamble: "cell-"
cells: 
  inhouse_queue_depth:
    dataRef: "telegraf-write-time"
    label:
      separator: "cr"
      units: "none"
      decimalPoints: 0
    labelColor:
      thresholdsRef: "queuedepth"
    linkRef: "grafana-home"
  inhouse_queue_count:
    dataRef: "influx-load-tester-metrics-per-sec"
    label:
      separator: "cr"
      units: "none"
      decimalPoints: 0
    labelColor:
      thresholdsRef: "queuecount"
    linkRef: "grafana-home"
  rabbitmq_queue_depth:
    dataRef: "test-data-large-sin"
    label:
      separator: "cr"
      units: "none"
      decimalPoints: 0
    labelColor:
      thresholdsRef: "queuedepth"
    linkRef: "grafana-home"
  rabbitmq_queue_count:
    dataRef: "telegraf-mem-usage"
    label:
      separator: "cr"
      units: "none"
      decimalPoints: 0
    labelColor:
      thresholdsRef: "queuecount"
    linkRef: "grafana-home"
  mem_queue_depth:
    dataRef: "test-data-large-sin"
    label:
      separator: "cr"
      units: "none"
      decimalPoints: 0
    labelColor:
      thresholdsRef: "queuedepth"
    linkRef: "grafana-home"
  db_transactions:
    dataRef: "test-data-large-sin"
    label:
      separator: "cr"
      units: "ops"
      decimalPoints: 0
    labelColor:
      thresholdsRef: "dbtrans"
    linkRef: "grafana-home"
  duplicate_lock_rate:
    dataRef: "telegraf-mem-usage"
    label:
      separator: "cr"
      units: "ops"
      decimalPoints: 0
    labelColor:
      thresholdsRef: "dbtrans"
    linkRef: "grafana-home"
  inhouse_queue_latency:
    dataRef: "influx-load-tester-metrics-per-sec"
    label:
      separator: "cr"
      units: "s"
      decimalPoints: 1
    labelColor:
      thresholdsRef: "queuelatency"
    linkRef: "grafana-home"
  wakeup_queue_latency:
    dataRef: "influx-load-tester-metrics-per-sec"
    label:
      separator: "cr"
      units: "s"
      decimalPoints: 1
    labelColor:
      thresholdsRef: "queuelatency"
    linkRef: "grafana-home"
  rabbitmq_latency:
    dataRef: "telegraf-mem-usage"
    label:
      separator: "cr"
      units: "s"
      decimalPoints: 1
    labelColor:
      thresholdsRef: "queuelatency"
    linkRef: "grafana-home"
  rabbitmq_slowness:
    dataRef: "telegraf-mem-usage"
    label:
      separator: "space"
      units: "s"
      decimalPoints: 1
    labelColor:
      thresholdsRef: "queuelatency"
    linkRef: "grafana-home"
    # GUrka