---

gradientMode: "hue"
cellIdPreamble: "cell-"
cells: 
  metrics-per-sec:
    dataRef: "telegraf-metrics-per-sec"
    label:
      separator: "cr"
      units: "none"
      decimalPoints: 0
    labelColor:
      thresholdsRef: "metrics-per-sec"
    linkRef: "metrics-per-sec"
  write-time:
    dataRef: "telegraf-write-time"
    label:
      separator: "cr"
      units: "ns"
      decimalPoints: 2
    labelColor:
      thresholdsRef: "write-time"
    linkRef: "write-time"
  mem-usage:
    dataRef: "telegraf-mem-usage"
    label:
      separator: "cr"
      units: "percent"
      decimalPoints: 0
    labelColor:
      thresholdsRef: "mem-usage"
    linkRef: "grafana-home"