---

links:
  grafana-home:
    url: "https://grafana.com/"
    params: "time"
  metrics-per-sec:
    url: "https://chronograf.vgthosting.net/sources/2/chronograf/data-explorer?query=SELECT%20non_negative_derivative%28last%28%22metrics_gathered%22%29%2C%201s%29%20FROM%20%22telegraf%22.%2260days%22.%22telegraf_internal_gather%22%20WHERE%20%22environment%22%20%3D%20%27test%27%20AND%20%22runtime_environment%22%20%3D%20%27sci%27%20AND%20time%3Enow%28%29-1h%20GROUP%20BY%20time%281m%29%20fill%28none%29"
  write-time:
    url: "https://chronograf.vgthosting.net/sources/2/chronograf/data-explorer?query=SELECT%20mean%28%22gather_time_ns%22%29%20AS%20%22mean_gather_time_ns%22%20FROM%20%22telegraf%22.%2260days%22.%22telegraf_internal_gather%22%20WHERE%20time%20%3E%20%3AdashboardTime%3A%20AND%20time%20%3C%20%3AupperDashboardTime%3A%20AND%20%22environment%22%3D%27test%27%20AND%20%22runtime_environment%22%3D%27sci%27%20AND%20%22site%22%3D%27eu-west-1%27%20GROUP%20BY%20time%28%3Ainterval%3A%29%20FILL%28null%29"
colors:
  red: "#FF0000"
  amber: "#FFBF00"
  green: "#00FF00"
cellColorMappings:
  darkTheme:
    red: "red"
    amber: "amber"
    green: "green"
  lightTheme:
    red: "light-red"
    amber: "light-orange"
    green: "light-green"

# The grafana variable has to impact a query, but if it does the first match
# per variable will be applied to the thresholds. If using with test-data you
# can get around this 'update' restriction by adding the variable to your panel title.
variableThresholdScalars:
  site:
    - {variableValuePattern: ".*Cicely.*", thresholdScalar: 2, cellIdPatternScope: [".*box.*"]}
  environment:
    - {variableValuePattern: "dev", thresholdScalar: 0.2, cellIdPatternScope: [".*box.*"]}

thresholds:
  write-time:
    - {color: "green", level: 10}
    - {color: "amber", level: 30}
    - {color: "red", level: 60}
  metrics-per-sec:
    - {color: "green", level: 200}
    - {color: "amber", level: 300}
    - {color: "red", level: 1500}
  dbtrans:
    - {color: "green", level: 200}
    - {color: "amber", level: 500}
    - {color: "red", level: 900}
  mem-usage:
    - {color: "green", level: 30}
    - {color: "amber", level: 60}
    - {color: "red", level: 90}
  normalized:
    - {color: "green", level: 0.4}
    - {color: "amber", level: 0.6}
    - {color: "red", level: 0.8}